"@generated by @aspect_rules_js//npm/private:npm_translate_lock.bzl from //:pnpm-lock.yaml"

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//js:defs.bzl", _js_library = "js_library")
load("@npm__balanced-match__1.0.2__links//:defs.bzl", store_0 = "npm_imported_package_store")
load("@npm__brace-expansion__1.1.11__links//:defs.bzl", store_1 = "npm_imported_package_store")
load("@npm__concat-map__0.0.1__links//:defs.bzl", store_2 = "npm_imported_package_store")
load("@npm__fs.realpath__1.0.0__links//:defs.bzl", store_3 = "npm_imported_package_store")
load("@npm__glob__7.2.3__links//:defs.bzl", store_4 = "npm_imported_package_store")
load("@npm__inflight__1.0.6__links//:defs.bzl", store_5 = "npm_imported_package_store")
load("@npm__inherits__2.0.4__links//:defs.bzl", store_6 = "npm_imported_package_store")
load("@npm__jasmine-core__4.3.0__links//:defs.bzl", link_7 = "npm_link_imported_package_store", store_7 = "npm_imported_package_store")
load("@npm__jasmine__4.3.0__links//:defs.bzl", link_8 = "npm_link_imported_package_store", store_8 = "npm_imported_package_store")
load("@npm__minimatch__3.1.2__links//:defs.bzl", store_9 = "npm_imported_package_store")
load("@npm__once__1.4.0__links//:defs.bzl", store_10 = "npm_imported_package_store")
load("@npm__path-is-absolute__1.0.1__links//:defs.bzl", store_11 = "npm_imported_package_store")
load("@npm__wrappy__1.0.2__links//:defs.bzl", store_12 = "npm_imported_package_store")

def npm_link_all_packages(name = "node_modules", imported_links = []):
    """Generated list of npm_link_package() target generators and first-party linked packages corresponding to the packages in //:pnpm-lock.yaml

    Args:
        name: name of catch all target to generate for all packages linked
        imported_links: optional list link functions from manually imported packages
            that were fetched with npm_import rules,

            For example,

            ```
            load("@npm//:defs.bzl", "npm_link_all_packages")
            load("@npm_meaning-of-life__links//:defs.bzl", npm_link_meaning_of_life = "npm_link_imported_package")

            npm_link_all_packages(
                name = "node_modules",
                imported_links = [
                    npm_link_meaning_of_life,
                ],
            )```
    """

    root_package = ""
    link_packages = [""]
    is_root = native.package_name() == root_package
    link = native.package_name() in link_packages
    if not is_root and not link:
        msg = "The npm_link_all_packages() macro loaded from @npm//:defs.bzl and called in bazel package '%s' may only be called in the bazel package(s) corresponding to the root package '' and packages ['']" % native.package_name()
        fail(msg)
    link_targets = []
    scope_targets = {}

    for link_fn in imported_links:
        new_link_targets, new_scope_targets = link_fn(name)
        link_targets.extend(new_link_targets)
        for _scope, _targets in new_scope_targets.items():
            scope_targets[_scope] = scope_targets[_scope] + _targets if _scope in scope_targets else _targets

    if is_root:
        store_0(name = "{}/balanced-match".format(name))
        store_1(name = "{}/brace-expansion".format(name))
        store_2(name = "{}/concat-map".format(name))
        store_3(name = "{}/fs.realpath".format(name))
        store_4(name = "{}/glob".format(name))
        store_5(name = "{}/inflight".format(name))
        store_6(name = "{}/inherits".format(name))
        store_7(name = "{}/jasmine-core".format(name))
        store_8(name = "{}/jasmine".format(name))
        store_9(name = "{}/minimatch".format(name))
        store_10(name = "{}/once".format(name))
        store_11(name = "{}/path-is-absolute".format(name))
        store_12(name = "{}/wrappy".format(name))
    if link:
        if native.package_name() == "":
            link_targets.append(link_7(name = "{}/jasmine-core".format(name)))
            link_targets.append(link_8(name = "{}/jasmine".format(name)))

    for scope, scoped_targets in scope_targets.items():
        _js_library(
            name = "{}/{}".format(name, scope),
            srcs = scoped_targets,
            tags = ["manual"],
            visibility = ["//visibility:public"],
        )

    _js_library(
        name = name,
        srcs = link_targets,
        tags = ["manual"],
        visibility = ["//visibility:public"],
    )
