# See https://docs.aspect.build/v/workflows/config
---
tasks:
  - format:
      queue: aspect-small
  - buildifier:
      queue: aspect-small
  - configure:
      queue: aspect-small
  - test:
  - delivery:
      always_deliver: true
