# See https://docs.aspect.build/v/workflows/config
---
tasks:
  - format:
      queue: aspect-small
  - buildifier:
      queue: aspect-small
  - configure:
      queue: aspect-small
  - test:
      bazel:
        flags:
          - --config=rbe
      hooks:
        - type: before_task
          command: mkdir -p /workflows/artifacts && vmstat -a -S M -t 1 2>&1 > /workflows/artifacts/vmstat.out &
        - type: after_task
          command: cat /workflows/artifacts/vmstat.out
  - delivery:
      auto_deliver: true
      rules:
        - deliverable: 'attr("tags", "\bdeliverable\b", //...)'
          condition:
            branches:
              - main
        - deliverable:
            - //docs:docs_delivery
          condition:
            only_on_change: false
            branches:
              - main
notifications:
  github: {}
