name: Aspect Workflows

on:
  # Triggers the workflow on pull request events and on main
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allow this to be triggered manually via the GitHub UI Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  aspect-workflows:
    name: Aspect Workflows
    uses: ./.github/workflows/.aspect-workflows-reusable.yaml
    with:
      queue: aspect-micro
